In [3]:
database_path = "/Users/achowd6/Codes/itac-report-validator/docs/report1/IACAssessmentTemplate.v2.1.xlsx"

import pandas as pd

# Read all sheets from the Excel file into a dictionary of DataFrames
all_sheets = pd.read_excel(database_path, sheet_name=None)

In [7]:
recommendation_info = all_sheets['Recommendation Info']

recommendation_info.head()

,RECOMMENDATIONS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,NaN,NaN,NaN,NaN,Primary,NaN,NaN,NaN,Secondary,NaN,...,NaN,NaN,NaN,NaN,NaN,Recource Stream Codes,NaN,NaN,BP Tool,NaN
1,NaN,ARC Code,APP Code,Additional Description,Resource Steam,Unit Savings,Unit,$ Savings,Resource Steam,Unit Savings,...,Rebates,NaN,NaN,NaN,Electricity Usage,EC,kWh (site),NaN,none,NaN
2,1.0,2.7211,NaN,HVAC Tune-Up To Increase Energy Efficiency,Electricity Usage,72020,kWh (site),8066,NaN,NaN,...,Y,NaN,NaN,NaN,Electricity Demand,ED,kW Months / yr,NaN,AM+,AirMaster+
3,2.0,2.4231,NaN,Reduce the Discharge Pressure of the compresse...,Electricity Usage,24928,kWh (site),2792,NaN,NaN,...,N,NaN,NaN,NaN,Electricity Fees,EF,no units,NaN,CWSAT,Chilled Water System Analysis Tool
4,3.0,2.7135,NaN,Install Occupancy Sensors,Electricity Usage,56313,kWh (site),6307,NaN,NaN,...,Y,NaN,NaN,NaN,Natural Gas,E2,MMBtu,NaN,FSAT,Fan System Assessment Tool (FSAT)

In [11]:
recommendation_info[2:3]

,RECOMMENDATIONS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
2,1.0,2.7211,NaN,HVAC Tune-Up To Increase Energy Efficiency,Electricity Usage,72020,kWh (site),8066,NaN,NaN,...,Y,NaN,NaN,NaN,Electricity Demand,ED,kW Months / yr,NaN,AM+,AirMaster+